"""
Conversation Memory component for the Manhattan AI Assistant.

This module retrieves previous conversations from the MySQL database,
constructs chronological conversation history, converts both previous
and current NLP outputs into LLM-compatible string representations,
and generates a message history for contextual response generation.

Conversation Memory is implemented as an independent component to
separate conversation retrieval and context construction from the
Large Language Model, improving modularity, maintainability,
and future extensibility.

Current Architecture:

    MySQL Conversation History
               ↓
    Retrieve Previous Conversations
               ↓
    Build Chronological Message History
               ↓
    Append Serialized NLP Output
               ↓
    LLM-Compatible Conversation Context
               ↓
    Performance Logging
               ↓
            MySQL

Author:
    Krishna Mahidhar

Project:
    Manhattan - Offline AI Assistant
"""

import threading
import pandas as pd
import time
from datetime import datetime
from mysql.connector import DatabaseError
import json
import database

class ConversationMemory(threading.Thread):
    """
    Conversation Memory module for the Manhattan AI Assistant.

    This class retrieves previous conversations from the MySQL database,
    constructs chronological conversation history, converts previous and
    current NLP outputs into string-based chat messages, and generates
    an LLM-compatible message history for contextual response generation.

    Conversation Memory is implemented as an independent module to
    separate conversation retrieval from the Large Language Model,
    allowing the memory component to evolve independently without
    affecting other parts of the application.

    Features:
    - Retrieves previous conversations from MySQL
    - Configurable conversation retrieval window
    - Constructs chronological conversation history
    - Generates LLM-compatible message history
    - Component-level performance monitoring
    - Exception handling and error logging

    Attributes:
        performance_log (dict):
            Stores execution metrics including conversation ID,
            execution timestamps, duration, status, and error
            information for performance monitoring.
    """
    def __init__(self):
        """
        Initialize the Conversation Memory module.

        Initializes the parent Thread class and prepares the
        performance logging dictionary used throughout the execution
        of the Conversation Memory component.

        The component name is assigned during initialization so that
        all performance records written to the performance_monitor
        table can be identified as belonging to the Conversation
        Memory module.
        """
        threading.Thread.__init__(self)
        self.performance_log = {}
        self.performance_log['component'] = 'ConversationMemory'
    def run(self, nl_processed_data, conversation_id = None):
        """
        Entry point for the Conversation Memory thread.

        This method retrieves previous conversations, constructs the
        conversation context required by the Large Language Model,
        and returns the LLM-compatible message history.

        The supplied conversation_id is propagated into the
        performance log so that Conversation Memory execution
        metrics can be linked back to the corresponding
        conversation_history row.

        Args:
            nl_processed_data (dict):
                Structured NLP output generated by the
                Natural Language Processing component.

            conversation_id (int | None, optional):
                Primary key of the current conversation_history
                row. Used to associate performance monitoring
                records with the current conversation.

        Returns:
            list[dict] | str:
                Returns the completed LLM-compatible message history,
                where each message is represented as a dictionary
                containing a role and a string content field.

                Returns an error message if conversation context
                generation fails.
        """
        self.performance_log['conversation_id'] = conversation_id
        memory_data = self.conversation_context(nl_processed_data)
        if memory_data:
            return memory_data
        else:
            return 'Error Occurred! Cannot be processed. Please check the logs.'
    def retrieve_conversation(self, row_limit = 10):
        """
        Retrieve previous conversations from the database.

        Fetches the most recent conversations from the
        conversation_history table and retains only the columns
        required for conversation context generation.

        The number of retrieved rows is configurable through
        the row_limit parameter.

        Args:
            row_limit (int, optional):
                Maximum number of previous conversation rows
                to retrieve from the database.
                Defaults to 10.

        Raises:
            DatabaseError:
                Raised if the database query fails.

            KeyError:
                Raised if one or more required columns are
                missing from the retrieved DataFrame.

        Returns:
            pandas.DataFrame:
                DataFrame containing:

                - raw_text
                - processed_text
                - ai_response
        """
        try:
            past_conversation = database.DatabaseManager().retrieve_conversation(row_limit)
            past_conversation = past_conversation.loc[:, ['raw_text', 'processed_text', 'ai_response']]
            return past_conversation
        except (KeyError, DatabaseError) as e:
            raise
    def conversation_context(self, nl_processed_data):
        """
        Construct conversation history for the Large Language Model.

        This method retrieves previous conversations from MySQL,
        converts them into chronological user-assistant message
        pairs, serializes the NLP output into a textual message for the
        LLM, and returns a message history compatible with LLM chat models.

        Workflow:
            1. Retrieve previous conversations.
            2. Reconstruct chronological user/assistant message history.
            3. Convert stored NLP output into JSON strings for LLM compatibility.
            4. Serialize the current NLP output into an LLM-compatible user message.
            5. Record execution metrics.
            6. Return completed conversation context.

        Args:
            nl_processed_data (dict):
                Structured NLP output representing the current
                user request.

        Returns:
            list[dict] | None:
                Returns a chronological list of dictionaries
                formatted as:

                [
                    {
                        "role": "user" | "assistant",
                        "content": "<string>"
                    }
                ]

                "content" always contains a string because Ollama's chat API
                expects message content to be textual.
                Structured NLP dictionaries are serialized before being
                added to the conversation history.

                Returns None if conversation context generation
                fails.

        Notes:
            Previous conversations are reconstructed dynamically
            for each request rather than storing duplicated
            conversation context inside the database.

            Stored NLP output is deserialized from the database
            and re-serialized into JSON strings before being
            supplied to the LLM. This preserves the complete
            structured NLP information while satisfying the
            chat API requirement that every message "content"
            field be a string.

            The current implementation retrieves the most recent
            configurable number of conversations before appending
            the current processed user input.
        """
        self.performance_log['start_time'] = time.time()
        try:
            conversation_history = []
            conversation = self.retrieve_conversation(row_limit=10)
            for i in range(conversation.index.start, conversation.index.stop):
                if pd.notna(conversation.processed_text[i]) \
                        and pd.notna(conversation.ai_response[i]):
                    conversation_history.append({
                        "role": "user",
                        "content": json.dumps(json.loads(conversation.processed_text[i]))
                    })
                    conversation_history.append({
                        "role": "assistant",
                        "content": str(conversation.ai_response[i])
                    })
            conversation_history.append(
                {
                    "role": "user",
                    "content": json.dumps(nl_processed_data)
                }
            )
            self.performance_log['status'] = 'Success'
            self.performance_log['error_message'] = None
            return conversation_history
        except Exception as e:
            self.performance_log['status'] = 'Error'
            self.performance_log['error_message'] = f'{type(e).__name__}: {e}'
            return None
        finally:
            self.performance_log['end_time'] = time.time()
            self.performance_monitor()

    def performance_monitor(self):
        """
        Record execution metrics for the Conversation Memory module.

        This method calculates execution duration, generates the
        current timestamp, and persists Conversation Memory
        performance information to the MySQL
        performance_monitor table.

        Workflow:
            1. Generate current timestamp.
            2. Calculate execution duration.
            3. Populate performance metrics.
            4. Persist metrics to MySQL.

        Metrics captured:
            - conversation_id
            - component name
            - start_time
            - end_time
            - duration
            - status
            - error_message

        The conversation_id field links the Conversation Memory
        performance log to the corresponding conversation_history
        row, allowing complete end-to-end conversation execution
        to be analyzed across all project components.

        Returns:
            None
        """
        now = datetime.now()
        self.performance_log['created_at'] = now.strftime("%Y-%m-%d %H:%M:%S")
        self.performance_log['duration'] = (self.performance_log['end_time'] -
                                            self.performance_log['start_time'])
        database.DatabaseManager().performance_monitor(perf_data=self.performance_log)
