"""
Large Language Model (LLM) component for the Manhattan AI Assistant.

This module acts as the reasoning and response-generation layer of the
Manhattan project. It receives structured Natural Language Processing (NLP)
output, retrieves relevant conversation history through the Conversation
Memory component, constructs a complete chat context, and generates the final
assistant response using an offline Ollama-hosted language model.

Unlike traditional chatbot implementations where memory handling is tightly
coupled with the language model, Manhattan separates conversation retrieval
into an independent Conversation Memory component. This allows memory
management strategies to evolve independently while keeping the LLM interface
unchanged.

Current Architecture:

    Structured NLP Output
               ↓
    Conversation Memory
               ↓
    Build LLM Conversation Context
               ↓
    System Prompt Injection
               ↓
    Ollama (Llama 3.2 : 3B)
               ↓
    AI Response Generation
               ↓
    Performance Logging
               ↓
            MySQL

Current responsibilities of this module:

- Accept structured NLP output from the Natural Language Processing component.
- Request relevant historical conversation context from Conversation Memory.
- Construct the final message list required by the Ollama Chat API.
- Inject Manhattan's system prompt defining assistant behaviour.
- Generate responses using an offline Large Language Model.
- Record execution metrics into the performance monitoring database.

Author:
    Sai Krishna Mahidhar Devulapalli

Project:
    Manhattan - Offline AI Assistant
"""

from ollama import chat
import time
from datetime import datetime
import threading
import database
import conversation_memory

class Manhattan(threading.Thread):
    """
    Large Language Model component for the Manhattan AI Assistant.

    This class represents Manhattan's reasoning engine. It coordinates
    Conversation Memory and the offline Ollama language model to generate
    context-aware responses for user requests.

    The class does not retrieve previous conversations directly from the
    database. Instead, it delegates conversation reconstruction to the
    Conversation Memory component, maintaining clear separation between
    memory management and language generation.

    Features:

    - Conversation-aware response generation
    - Offline Llama model inference through Ollama
    - Configurable system prompt
    - Independent Conversation Memory integration
    - Component-level performance monitoring
    - Exception handling and error logging

    Attributes:

        model_name (str):
            Name of the Ollama model used for inference.

        performance_log (dict):
            Dictionary storing execution metadata including
            conversation_id, execution timestamps, duration,
            execution status and error information for
            performance monitoring.
    """
    def __init__(self):
        """
        Initialize the Manhattan language model component.

        This constructor initializes the parent Thread class,
        configures the Ollama model name to be used for inference,
        and prepares the performance logging dictionary used
        throughout Manhattan execution.

        The performance logging structure is initialized once so
        that every inference request records execution timing,
        conversation association and execution status.
        """
        threading.Thread.__init__(self)
        self.model_name = 'llama3.2:3b'
        self.performance_log = {}
        self.performance_log['component'] = 'Manhattan'
    def run(self, nl_processed_data, conversation_id = None):
        """
        Execute the complete language model workflow.

        This method serves as the public execution entry point
        for the Manhattan component.

        The supplied structured NLP output is first forwarded to
        the Conversation Memory component, which retrieves relevant
        historical conversations and constructs an LLM-compatible
        message history.

        If conversation context construction succeeds, the message
        history is forwarded to the chat() method where the
        language model generates the final assistant response.

        The supplied conversation_id is propagated into the
        performance log so that Manhattan execution metrics
        can be linked back to the corresponding
        conversation_history row.

        Args:

            nl_processed_data (dict):
                Structured NLP output generated by the
                Natural Language Processing component.

            conversation_id (int | None, optional):
                Primary key of the current
                conversation_history row.

        Returns:

            tuple[str | None, list[dict]]:
                On successful execution returns:

                (
                    assistant_response,
                    conversation_history
                )

                assistant_response contains the generated
                LLM response.

                conversation_history contains the complete
                LLM-compatible message history used for
                inference.

            str | None:
                Failure:

                (
                    None,
                    error_message
                )

                Returns None and error message if Conversation
                Memory fails to construct conversation
                context.
        """
        self.performance_log['conversation_id'] = conversation_id
        conversation_history  = conversation_memory.ConversationMemory().run(nl_processed_data, conversation_id)
        if conversation_history != 'Error Occurred! Cannot be processed. Please check the logs.':
            return self.chat(user_input=conversation_history), conversation_history
        else:
            return None, conversation_history
    def chat(self, user_input):
        """
        Generate a response using the offline language model.

        This method constructs the final message list required by
        the Ollama Chat API.

        The conversation history supplied by Conversation Memory
        is combined with Manhattan's system prompt, producing the
        complete context supplied to the language model.

        The method performs synchronous inference using the
        configured Ollama model and records execution timing,
        status and error information for performance monitoring.

        Args:

            user_input (list[dict]):
                LLM-compatible conversation history.

                Each message contains:

                {
                    "role":
                        "system" |
                        "user" |
                        "assistant",

                    "content": "<string>"
                }

        Returns:

            str:
                Assistant response generated by the language model.

            None:
                Returned when inference fails due to any
                unexpected exception.

        Notes:

            Conversation Memory is responsible for determining
            which previous conversations are supplied to the
            language model.

            Manhattan only performs response generation using
            the supplied conversation history.

            The current implementation uses:

            - Ollama
            - Llama 3.2 : 3B
            - Temperature = 0.3
            - Context Window = 16384 tokens
            - keep_alive = 10 minutes
        """
        try:
            self.performance_log['start_time'] = time.time()
            messages = [
                {
                    'role': 'system',
                    'content': ('''
                    You are Manhattan, an offline AI assistant.
                    Personality:
                        - Intelligent, witty and occasionally sarcastic.
                        - Use light, playful sarcasm when it naturally fits the conversation.
                        - Never use sarcasm to insult, belittle or humiliate the user.
                        - Keep humor brief and relevant.
                    Behavior:
                        - Answer the user's latest request accurately.
                        - Use previous conversation only when relevant.
                        - Do not reveal internal reasoning.
                        - If there is insufficient information, say so clearly.
                        - Respond in plain text.
                    '''
                    )
                }
            ]
            messages.extend(user_input)
            response = chat(model=self.model_name, messages=messages,
                            options={'temperature': 0.3, 'num_ctx': 16384, 'keep_alive': '10m'},
                            stream=False
                            )
            self.performance_log['status'] = 'Success'
            self.performance_log['error_message'] = None
            return response['message']['content']
        except Exception as e:
            self.performance_log['status'] = 'Error'
            self.performance_log['error_message'] = f'{type(e).__name__}: {e}'
            return None
        finally:
            self.performance_log['end_time'] = time.time()
            self.performance_monitor()
    def performance_monitor(self):
        """
        Record execution metrics for the Manhattan component.

        This method calculates total inference duration,
        generates the current timestamp and persists
        Manhattan performance information into the
        performance_monitor table.

        Workflow:

            1. Generate current timestamp.
            2. Calculate execution duration.
            3. Populate performance metrics.
            4. Persist metrics to MySQL.

        Metrics captured:

            - conversation_id
            - component name
            - start_time
            - end_time
            - duration
            - status
            - error_message

        The conversation_id field links the Manhattan
        performance log to the corresponding
        conversation_history row, allowing complete
        end-to-end execution analysis across all
        Manhattan components.

        Returns:

            None
        """
        now = datetime.now()
        self.performance_log['created_at'] = now.strftime("%Y-%m-%d %H:%M:%S")
        self.performance_log['duration'] = (self.performance_log['end_time'] -
                                            self.performance_log['start_time'])
        database.DatabaseManager().performance_monitor(perf_data=self.performance_log)
