"""
Natural Language Processing module for the Manhattan project.

This module defines the NaturalLanguageProcessing class, which is responsible
for performing spaCy-based text preprocessing on speech-to-text output generated
by the Speech Recognition component.

Current responsibilities of this module:
- Convert raw transcription text into a spaCy Doc object.
- Extract sentence-level segmentation from the transcription.
- Perform Named Entity Recognition (NER).
- Build an entity summary grouped by entity labels.
- Perform token-level linguistic analysis such as token text, lemma, and
  part-of-speech (POS) tagging.
- Log component performance details such as start time, end time, duration,
  execution status, and error information into the performance monitoring table.

This module is designed as an intermediate NLP processing layer in Manhattan's
pipeline, where transcribed text is enriched with structured linguistic
information before being used by downstream components.

Dependencies:
- spaCy
- en_core_web_sm model
- database module for performance logging
- threading, datetime, time, warnings
"""

import threading
import database
from datetime import datetime
import spacy
import time
import warnings
warnings.filterwarnings('ignore') #To suppress all warnings across the entire script


class NaturalLanguageProcessing(threading.Thread):
    """
    Thread-based Natural Language Processing component for the Manhattan project.

    This class accepts raw transcribed text, converts it into a spaCy Doc object,
    and generates a structured NLP output package containing sentence detection,
    named entities, grouped entity summaries, and token-level linguistic analysis.

    The class also records execution timings and logs success or failure details
    into the performance monitoring system.

    Attributes:
        nlp (spacy.language.Language):
            Loaded spaCy English language pipeline used for text processing.

        raw_text (spacy.tokens.doc.Doc):
            spaCy Doc object created from the raw transcription text.

        performance_log (dict):
            Dictionary used to capture component-level execution metadata such as
            component name, start time, end time, duration, status, and
            error_message for database logging.
    """
    def __init__(self, raw_text):
        """
            Initialize the NaturalLanguageProcessing component.

            This constructor loads the spaCy English model, converts the supplied
            transcription text into a spaCy Doc object, and initializes the
            performance logging dictionary for the NLP component.

            Args:
                raw_text (str):
                    Raw text generated by the speech-to-text component. This text is
                    converted into a spaCy Doc object for downstream NLP analysis.

            Raises:
                OSError:
                    If the spaCy language model 'en_core_web_sm' is not installed or
                    cannot be loaded.

                Exception:
                    Propagates any unexpected initialization error encountered during
                    spaCy model loading or Doc creation.
        """
        threading.Thread.__init__(self)
        self.nlp = spacy.load('en_core_web_sm')
        self.raw_text = self.nlp(raw_text)
        self.performance_log = {}
        self.performance_log['component'] = 'NaturalLanguageProcessing'

    def run(self):
        """
            Execute the NLP preprocessing pipeline for the current transcription.

            This method acts as the thread entry point and delegates the actual
            processing work to the preprocessing() method.

            Returns:
                dict:
                    A structured dictionary containing the original transcription,
                    sentence segmentation, named entities, grouped entity summary,
                    and token-level analysis.
        """
        return self.preprocessing()

    def preprocessing(self):
        """
            Build the complete NLP output package for the current transcription.

            This method is the main orchestration layer of the NLP component. It
            performs the following operations on the current spaCy Doc object:

            1. Extract the original text from the Doc.
            2. Perform sentence detection.
            3. Perform Named Entity Recognition (NER).
            4. Generate an entity summary grouped by entity label.
            5. Perform token-level analysis, including token text, lemma, and
                part-of-speech (POS).

            The method also records execution timings and logs success or failure
            information into the performance monitoring system.

            Returns:
                dict:
                    A dictionary containing the processed NLP output with the
                    following keys:

                    - original_text (str):
                        Original transcription text.

                    - sentences (list[str]):
                        List of sentence strings extracted from the transcription.

                    - entities (list[dict] | None):
                        List of detected named entities, where each entity is
                        represented as a dictionary containing:
                            - text: entity text
                            - label: spaCy entity label
                        Returns None if no entities are detected.

                    - entity_summary (dict | None):
                        Dictionary grouping entity texts by their entity label.
                        Example:
                            {
                                "PERSON": ["Narendra Modi"],
                                "GPE": ["Japan"]
                            }
                        Returns None if no entities are detected.

                    - token_analysis (list[dict] | None):
                        List of token-level linguistic details, where each token is
                        represented as a dictionary containing:
                            - text: original token text
                            - lemma: lemmatized/base form of the token
                            - pos: part-of-speech tag
                        Returns None if token analysis produces no tokens.

            Raises:
                Exception:
                    Propagates any exception raised by sentence detection, named
                    entity recognition, entity summary generation, or token analysis
                    after updating performance logging metadata.
        """
        self.performance_log['start_time'] = time.time()
        try:
            preprocessed_text = {
                'original_text': self.raw_text.text,
                'sentences': self.sentence_detection(self.raw_text),
                'entities': self.named_entity_recognition(self.raw_text),
                'entity_summary': self.entity_summary(self.raw_text),
                'token_analysis': self.token_analysis(self.raw_text)
            }
            self.performance_log['end_time'] = time.time()
            self.performance_log['status'] = 'Success'
            self.performance_log['error_message'] = None
            self.performance_monitor()
            return preprocessed_text
        except Exception as e:
            if self.performance_log.get('error_message'):
                self.performance_log['error_message'] += str(e)
            else:
                self.performance_log['error_message'] = str(e)
            self.performance_log['status'] = 'Error'
            self.performance_log['end_time'] = time.time()
            self.performance_monitor()

    def sentence_detection(self, text):
        """
            Extract sentence strings from a spaCy Doc object.

            This method uses spaCy sentence segmentation to split the supplied Doc
            into individual sentences and returns them as a list of strings.

            Args:
                text (spacy.tokens.doc.Doc):
                    spaCy Doc object containing the transcription text to be split
                    into sentences.

            Returns:
                list[str]:
                    List of sentence strings detected in the transcription.

            Raises:
                Exception:
                    Raised if no sentences are detected in the supplied text, or if
                    any unexpected error occurs during sentence extraction.
        """
        try:
            sentence = [str(sentence) for sentence in text.sents]
            if sentence:
                return sentence
            else:
                raise Exception('No sentences detected')
        except Exception as e:
            self.performance_log['error_message'] = str(e) + '\n'
            raise

    def named_entity_recognition(self, preprocessed_text_sentence):
        """
            Perform Named Entity Recognition (NER) on a spaCy Doc object.

            This method extracts all named entities identified by spaCy in the
            supplied Doc and returns them as a list of dictionaries. Each dictionary
            contains the entity text and its corresponding entity label.

            Args:
                preprocessed_text_sentence (spacy.tokens.doc.Doc):
                    spaCy Doc object on which named entity recognition is to be
                    performed.

            Returns:
                list[dict] | None:
                    A list of dictionaries representing detected named entities.
                    Each dictionary contains:
                        - text (str): the entity text
                        - label (str): spaCy entity label for the entity

                Returns None if no named entities are detected.

            Raises:
                Exception:
                    Propagates any unexpected error encountered during entity
                    extraction after updating the performance log.
        """
        try:
            ner = [
                {'text': token.text, 'label': token.label_}
                for token in preprocessed_text_sentence.ents
            ]
            if ner:
                return ner
            else:
                return None
        except Exception as e:
            self.performance_log['error_message'] = str(e) + '\n'
            raise
    def entity_summary(self, preprocessed_text_sentence):
        """
            Build a grouped summary of named entities by entity label.

            This method iterates through the named entities detected in the supplied
            spaCy Doc object and groups them into a dictionary keyed by entity
            labels such as PERSON, ORG, DATE, GPE, and others.

            Example output:
                {
                    "PERSON": ["Narendra Modi", "Sanae Takaichi"],
                    "GPE": ["India", "Japan"],
                    "DATE": ["tomorrow"]
                }

            Args:
                preprocessed_text_sentence (spacy.tokens.doc.Doc):
                    spaCy Doc object whose named entities are to be grouped.

            Returns:
                dict | None:
                    Dictionary mapping each entity label to a list of entity texts.
                    Returns None if no named entities are detected.

            Raises:
                Exception:
                    Propagates any unexpected error encountered while building the
                    grouped entity summary after updating the performance log.
        """
        try:
            entity_summary = {}
            for token in preprocessed_text_sentence.ents:
                if entity_summary.get(token.label_):
                    entity_summary[token.label_].append(token.text)
                else:
                    entity_summary[token.label_] = [token.text]
            if entity_summary:
                return entity_summary
            else:
                return None
        except Exception as e:
            self.performance_log['error_message'] = str(e) + '\n'
            raise
    def token_analysis(self, preprocessed_text_sentence):
        """
            Perform token-level linguistic analysis on a spaCy Doc object.

            This method iterates through all tokens present in the supplied spaCy
            Doc and extracts token-level linguistic metadata such as:

            - text: original token text
            - lemma: lemmatized/base form of the token
            - pos: part-of-speech tag assigned by spaCy

            Args:
                preprocessed_text_sentence (spacy.tokens.doc.Doc):
                    spaCy Doc object whose tokens are to be analyzed.

            Returns:
                list[dict] | None:
                    List of dictionaries containing token-level linguistic
                    information. Each dictionary contains:
                        - text (str): original token text
                        - lemma (str): lemmatized/base form of the token
                        - pos (str): part-of-speech tag

                    Returns None if no tokens are available for analysis.

            Raises:
                Exception:
                    Propagates any unexpected error encountered during token
                    analysis after updating the performance log.
        """
        try:
            analyzed_token = [
                {'text': token.text, 'lemma': token.lemma_, 'pos': token.pos_}
                for token in preprocessed_text_sentence
            ]
            if analyzed_token:
                return analyzed_token
            else:
                return None
        except Exception as e:
            self.performance_log['error_message'] = str(e) + '\n'
            raise
    def performance_monitor(self):
        """
            Log NLP component execution details to the performance monitoring table.

            This method finalizes the performance log by adding:
            - created_at timestamp
            - execution duration

            It then forwards the performance metadata to the database logging layer
            for insertion into the performance monitoring table.

            The performance log is expected to contain:
                - component
                - start_time
                - end_time
                - status
                - error_message

            Side Effects:
                Inserts a performance monitoring record into the database via
                database.log(...).performance_monitor().

            Returns:
                None
        """
        now = datetime.now()
        self.performance_log['created_at'] = now.strftime("%Y-%m-%d %H:%M:%S")
        self.performance_log['duration'] = (self.performance_log['end_time'] -
                                            self.performance_log['start_time'])
        database.log(data=self.performance_log).performance_monitor()